name: Pylint

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.13
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        sudo apt-get install sed
    - name: Retrieve rating from Pylint and Edit Readme
      run: bash ./scripts/pylint-rating.sh
    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        add: 'README.md'
        message: '[Github Actions] Update Readme with pylint rating.'
